package Model;

import android.content.Context;

import java.util.Random;

import DrawableObjects.Card;


/**
 * CardGenerator generates a Card with a
 * pattern attribute chosen at random.
 *
 * @author Varun Sriram
 * @version 1.5
 * @since 2014-11-28
 *
 */


public class CardGenerator
{

    /**
     * DEFAULTNUMPATTERNATTR: integer value representing the default number
     * of pattern attributes for a Card
     *
     */

    private static final int DEFAULTNUMPATTERNATTR = 4;


    /**
     * DEFAULTPOSX: float value representing the default x position
     * of the Card on the screen.
     *
     * DEAFULTPOSY: float value representing the default y position
     * of the Card on the screen.
     *
     */

    private static final float DEFAULTPOSX = 0.0f,
                               DEFAULTPOSY = -0.2f;


    /**
     * random: Random instance to be used to generate random
     *         numbers.
     *
     */

    private Random random;


    /**
     * numOfPatternAttr: integer value representing the number of
     *                   pattern attributes that will be used to
     *                   generate different cards.
     *
     * currentColor: integer representing the current pattern
     *                 of the Card.
     *
     * prevColor: integer representing the previous pattern
     *              of the Card.
     *
     */

    private int numOfPatternAttr,
                currentColor,
                prevColor;


    /**
     * Default constructor for CardGenerator class.
     *
     */

    public CardGenerator()
    {
        random = new Random();

        this.numOfPatternAttr = DEFAULTNUMPATTERNATTR;
        this.prevColor = 0;
        this.currentColor = 0;
    }


    /**
     * Constructor with a value for CardGenerator class.
     *
     * @param numOfPatterns: integer value representing the number of
     *                       pattern attributes that will be used to
     *                       generate different cards.
     */

    public CardGenerator(int numOfPatterns)
    {
        this();

        if(numOfPatterns > -1)
            this.numOfPatternAttr = numOfPatterns;
    }


    /**
     * Generates a Card using random integer attribute.
     *
     * @return card: Card instance representing the new Card
     *               generated with a random attribute.
     *
     */

    public Card generateCard(Context context)
    {

        this.generateColor();

        Card card = new Card(context, DEFAULTPOSX, DEFAULTPOSY, this.currentColor);

        return card;
    }


    /**
     * Gets a random integer using random.nextInt method.
     *
     * @see java.util.Random
     *
     * @param low: integer value representing the lowest
     *             value to start generating. Inclusive.
     *
     * @param high: integer value representing the highest
     *              value to end generating. Exclusive.
     *
     * @return R: integer value representing the random
     *            integer generated by the random.nextInt
     *            method.
     *
     */

    private int getRandValue(int low, int high)
    {
        int R = random.nextInt(high-low) + low;
        return R;
    }


    /**
     * Generates a random color and checks if the generated
     * color is the same color as the previous. If it is the
     * method keeps generating a random color until they are
     * different.
     *
     */

    private void generateColor()
    {
        this.currentColor = this.getRandValue(1, this.numOfPatternAttr + 1);

        while (this.currentColor == this.prevColor)
            this.currentColor = this.getRandValue(1, this.numOfPatternAttr + 1);


        this.prevColor = this.currentColor;

    }

}