package com.example.owner.gameproject;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;

import java.util.Random;


/**
 * Card represents a colored rectangular element
 * located at the center of the screen which the
 * user matches to one of the four colored circles
 * at the sides of the screen.
 *
 * @author Robert
 * @version 1.5
 * @since 2015-02-27
 *
 */

public class Card
{

    private final Paint red, blue, green;
    private TextObject word;
    public String WORDSTRING;


    /**
     * color android.graphics.Paint instance representing the color of the word.
     *
     */

    private int color = 0;
    private TextObject backToMenu;


    /**
     * Constructor for the Card class.
     *
     */

    public Card(Typeface typeface, int color)
    {
        WORDSTRING = randomColorString();
        this.word = new TextObject("Blue", (540f/1080)*GameView.WIDTH, (1100f/1701)*GameView.HEIGHT, typeface, color, (250f/1080) * GameView.WIDTH);

        this.red = new Paint();
        this.red.setColor(ColorsLoader.loadColorByName("red"));


        this.blue = new Paint();
        this.blue.setColor(ColorsLoader.loadColorByName("blue"));


        this.green = new Paint();
        this.green.setColor(ColorsLoader.loadColorByName("green"));

    }

    private String randomColorString() {

        return "Blue";
    }


    /**
     * Gets a random integer using random.nextInt method.
     *
     * @see java.util.Random
     *
     * @param low integer value representing the lowest
     *             value to start generating. Inclusive.
     *
     * @param high integer value representing the highest
     *              value to end generating. Exclusive.
     *
     * @return integer value representing the random integer generated by the
     *         random.nextInt method.
     *
     */

    private int getRandValue(int low, int high)
    {
        Random random = new Random();
        int randomInt = 99999;

        while(randomInt!=color)
            randomInt = random.nextInt(high-low) + low;

        return randomInt;
    }

    /**
     * Draws to android's canvas.
     *
     * @see android.graphics.Canvas
     * @param canvas Canvas instance representing android.graphics.Canvas class.
     */

    public void draw(Canvas canvas)
    {
        this.word.draw(canvas);

    }

    public int getColorId()
    {
        return color;
    }



}
